name: Build and Deploy

on:
  push:
    branches:
      - master  # or your default branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'  # specify your Node.js version
      - name: Install and Build
        run: |
          npm install
          npm run build
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: vuepress-build
          path: .vuepress/

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: vuepress-build
          path: .vuepress/
      - name: Configure Git
        run: |
          git config --global user.email "me@patrickwu.space"
          git config --global user.name "Jinming Wu, Patrick"
      - name: Clone and Deploy
        env:
          TOKEN: ${{ secrets.DEPLOY_TOKEN }}  # You'll need to set this in your repository secrets
        run: |
          git clone --depth 1 https://patrick:${TOKEN}@code.wedotstud.io/wslu/website.git website
          cp -rf ./.vuepress/dist/* ./website/wslu/
          cd website
          git add -A
          git commit -m "wslu Wiki update at $(date)"
          git push

